### ISSUE TITLE
[Bug] furyn and furyr do not use default get('BarbarianLevel')

### ISSUE THREAD

**Issue by LucienBreitkopf** [Croebh/Avrae-Customizations#20]
Snippets furyn and furyr

**Describe the bug**
Without having a linked dndbeyond account, furyn and furyr are not usable, prompting the user to instead connect their discord account with dndbeyond. Dicecloud/GoogleSheet users cannot make use of the snippet as is.

**To Reproduce**
1. Have no dndbeyond account connected with discord
2. Use furyr or furyn snippet in attack
3. Instead of attack resolving, account connection prompt appears.

**Expected behavior**
A generic snippet like this should not require a connected account.

**Screenshots**
![furyr](https://user-images.githubusercontent.com/65873436/96882064-322acd00-147f-11eb-9ea6-818fd9198ac2.jpg)

**Additional context**
Easily adjustable by using int(get('BarbarianLevel')) like towards the end of the snippet instead of int(BarbarianLevel).
Hope this was not intentional :)

**Comment by Croebh** [comment]
It's a snippet for a non-srd subclass, so yes this is intentional.
