### ISSUE TITLE
[Bug] !conc not adding the right bonus from !bladesong

### ISSUE THREAD

**Issue by itggot-markus-moen** [Croebh/Avrae-Customizations#29]
**What alias/snippet is this for?**
!conc

**Describe the bug**
A +1 is added when !conc is used, rather than the intelligence modifier of the character. The result is the same with both the !bladesong effect and with the bs argument to !conc.

**To Reproduce**
1. Create a bladesinger wizard with an intelligence modifier other than +1.
2. Add the character to Avrae.
3. Add to initiative.
4. Activate !bladesong.
5. Use !conc.

**Expected behavior**
That the intelligence modifier to be added to !conc, rather than +1. In my case I expected either a +3 or a +5, but both characters gave a +1.

**Screenshots**
![conc](https://user-images.githubusercontent.com/35598540/102225692-ccd7e300-3ee7-11eb-83ac-527112b75943.PNG)

**Comment by Croebh** [comment]
Aah, I was using constitution for some reason. Fixed.
