### ISSUE TITLE
`-h`option for `!ispellbook` [Feature Request]

### ISSUE THREAD

**Issue by RobbeA-1952396** [Croebh/Avrae-Customizations#33]
**What alias/snippet is this for?**
`!ispellbook`

**Is your feature request related to a problem? Please describe.**
When you want to, as the dm, check your monster's spellslots you don't want all the players to see it.

**Describe the solution you'd like**
A `-h` option to pm you instead. (if that's even possible)

**Describe alternatives you've considered**
Taking notes, ew

**Additional context**
/

**Comment by Croebh** [comment]
Its not, sadly
