### ISSUE TITLE
[Bug] wmsurge doesn't roll as intended

### ISSUE THREAD

**Issue by jfreemanhargis** [Croebh/Avrae-Customizations#52]
**What alias/snippet is this for?**
wmsurge

**Describe the bug**
Case mismatch is preventing the alias from displaying corresponding rolls.

**To Reproduce**
!wmsurge 12

**Expected behavior**
Those surge items with a roll would display the roll in the embed.
!wmsurge 12 should roll 1d10 but doesn't display it.

**Additional context**
!wmsurge gvar has "type":"roll" but code (line 20) is checking for `f" -f 'Roll|{Roll}'" if surge.type=='Roll'` Changing that to a lowercase 'roll' in a local version fixed the issue.

**Comment by Croebh** [comment]
Hopefully should be fixed now! Thanks for filing the issue
