### ISSUE TITLE
[Bug] !map throws a "str object is not callable" error

### ISSUE THREAD

**Issue by jjl2357** [Croebh/Avrae-Customizations#59]
**What alias/snippet is this for?**
!map

**Describe the bug**
After newly subscribing to the Map Utilities alias, entering the !map command resulted in this error:

Error on line 1, col 21:
for overNum in [""]+[str(x) for x in range(1,11)]:
                     ^
TypeError: 'str' object is not callable

**To Reproduce**
1. Add Avrae and Map Utilities to a server
2. Type !map to create a new map
3. Error

**Expected behavior**
A map should have been created.

**Comment by Croebh** [comment]
Sorry, have been very distracted IRL. Unfortunately not sure what would have caused this, but its possible its been fixed in other updates. If this happens again, please feel free to reopen this issue.
