### ISSUE TITLE
!map -bg <url.gif>

### ISSUE THREAD

**Issue by DMFelipeAlencar** [Croebh/Avrae-Customizations#61]
**What alias/snippet is this for?**

Firstly of all I loved what is already available.
Secondly my players are freaking out with this experience, there immersion is so good.
Above all I just want to ask to use gif maps like dynamic dungeons.

**Is your feature request related to a problem? Please describe.**
Just a request, map as a gif is awsome and would be great to work with it, but till now is not possible with avrae, could you please get this working?

I have tried change format without success.

**Describe the solution you'd like**
So please make this possible.

!map -bg <url.gif>

**Describe alternatives you've considered**
!map -bg <url.png> animated or other format

Thanks in advance.

**Comment by Croebh** [comment]
Sorry for the long delay, been tied up IRL.

Unfortunately this is not something that I am able to add, it would have to be supported by OTFBM, the website the aliases use to display the map. You could make a request (if someone else hasn't already) at https://github.com/otfbm/issues
