### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by VladFurman** [Croebh/Avrae-Customizations#76]
**What alias/snippet is this for?**
!ispellbook

**Describe the bug**
Certain spells don't show up in the spellbook, and don't notify that they don't show up, such as Silvery Barbs.

**To Reproduce**
1. Add a caster with Silvery Barbs (1st level spell)
2. Use `!ispellbook [caster]`
3. Silvery Barbs does not appear.

**Expected behavior**
Ideally, show all spells correctly; but if a spell isn't known, it should probably be marked similarly to how !sb does it: mark them as unknown.

**Screenshots**
<img width="358" alt="Capture" src="https://user-images.githubusercontent.com/5605369/152323092-5f087413-edf9-4565-aeaf-cb7619d85744.PNG">

**Comment by Croebh** [comment]
Updated gvar, now has up to date spell content
