### ISSUE TITLE
[Bug] `!font` alias is not using or creating spell slots

### ISSUE THREAD

**Issue by smita313** [Croebh/Avrae-Customizations#79]
**What alias/snippet is this for?**
`!font`

**Describe the bug**
`!font spend <level>` and `!font create <level>` are not correctly modifying spell slot counters

**To Reproduce**
On a sorcerer character with Font of Magic, attempt `!font spend 1` to create 1 Sorcery Point. See that no spell slot was actually spent.
On a sorcerer character with Font of Magic, attempt `!font create 1` to create a 1st level spell slot. See that no spell slot was actually created.

**Expected behavior**
When `!font spend <level>` is used, <level> sorcery points should be created and one <level> spell slot should be used.
When `!font create <level>` is used, the correct number of sorcery points to create one <level> spell slot should be used and the spell slot should be created.

**Screenshots**
<img width="527" alt="Screen Shot 2022-02-20 at 11 57 49 AM" src="https://user-images.githubusercontent.com/5431325/154857208-e07d2d8e-1f1c-4821-bb7f-6292d3b58bdd.png">
Here, the user spent a 2nd level spell slot with Chromatic Orb and has 2 remaining. Then the user attempts to spend a 2nd level spell slot to create 2 sorcery points. The sorcery points are created, but the number of spell slots remaining is not changed.

**Additional context**
It appears that the `!font` alias was modified 3 days ago, so it seems like this was newly introduced. Thanks for taking the time to look into this!

**Comment by Croebh** [comment]
Fixed!
