### ISSUE TITLE
[Bug] Using offset reverts every change done so far, as does grid sieze (c<#>)

### ISSUE THREAD

**Issue by Tosh0kan** [Croebh/Avrae-Customizations#86]
What title says. I try to set my map to size 100, but when I try to offset it, it undoes the map size.

**Comment by Croebh** [comment]
Can you provide more details?  There should have been a whole template that came up when you went to open the report:

```
**What alias/snippet is this for?**


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

```

Specifically, what commands exactly did you run, with what arguments?

**Comment by Tosh0kan** [comment]
Ah, sorry. It must have selected and overwrote when I wrote my question. Here:

**What alias/snippet is this for?**
Map Utilities

**Describe the bug**
I try to offset the map position after changing the map's size but when I do, the changes to the map size is undone.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to a channel running Map Utilities
2. Type `!map -options c100` then press enter
3. Type `!map -options o40x0` then press enter.
4. See error

**Expected behavior**
Offset command not revert map size option

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by Croebh** [comment]
Not an error:
![image](https://user-images.githubusercontent.com/5848891/189454134-d15df0bf-0c5c-4052-9340-db9cdae8a098.png)
As found in `!map help manage`

**Comment by Tosh0kan** [comment]
AH okay. Thank you!
