### ISSUE TITLE
[Bug]"True" instead of bob

### ISSUE THREAD

**Issue by D0ppl3gng3r** [Croebh/Avrae-Customizations#89]
**What alias/snippet is this for?**
!equip <weapon style> 2h name Bob

**Describe the bug**
It's naming it True.. 
**To Reproduce**
1. Go to any server you have it o 
3. Type in the snippet
4. Hit enter
5. See error

**Expected behavior**
To hit someone with Bob 😆 
**Screenshots**

**Additional context**

**Comment by Croebh** [comment]
`-name Bob` not `name Bob`

**Comment by D0ppl3gng3r** [comment]
Wow dude your fast thank you
