### ISSUE TITLE
[Bug] Using -spell when placing an overlay

### ISSUE THREAD

**Issue by nerdsanddragons** [Croebh/Avrae-Customizations#9]
**What alias/snippet is this for?**
!map

**Describe the bug**
when running the command !map -t <target> -spell <spell> -aim <aim target> it produces the error...
```py
Error on line 4, col 0:
serverTokens.update(userTokens)
^
Traceback (most recent call last):
ValueError: dictionary update sequence element #0 has length 1; 2 is required
This is an issue in a user-created command; do not report this on the official bug tracker.
```
**To Reproduce**
See description above

**Expected behavior**
It should place the overlay that has been saved for the spell listed in the json

**Comment by Croebh** [comment]
What's the exact command used?

**Comment by nerdsanddragons** [comment]
!map -t prix -spell colorspray -aim go1|stick

Doesn't produce the error but now just says:

Be sure to have a -t/-aim of using {targ} and {aim}

**Comment by Croebh** [comment]
Fixed with https://github.com/Croebh/Avrae-Customizations/commit/2228b2816838a5a3595ffa9eccbdd5853aa59b50
